openapi: 3.0.0
info:
  title: Upload API
  version: 1.0.0
  description: Upload single or multiple images to S3

paths:
  /api/v1/upload:
    post:
      summary: Upload a single image
      tags:
        - Upload
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        "200":
          description: File uploaded successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          location:
                            type: string
                            description: S3 file URL
        "400":
          description: Validation error / missing file / file too large
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/upload/multiple:
    post:
      summary: Upload multiple images
      tags:
        - Upload
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                images:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        "200":
          description: Files uploaded successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ApiResponse"
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          locations:
                            type: array
                            items:
                              type: string
                              description: S3 file URL
        "400":
          description: Validation error / missing files / files too large
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    ApiResponse:
      type: object
      properties:
        message:
          type: string
        success:
          type: boolean
        data:
          nullable: true
          type: object

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        success:
          type: boolean
        data:
          nullable: true
          type: object
